name = "nextjs-app"
compatibility_date = "2024-03-04"

compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "kv"
id = "09aae50deed5487cba0c2ddddecef496"

[[d1_databases]]
binding = "d1"
database_name = "d1"
database_id = "bb8093e0-0ccc-40c8-b784-ec6d14e7bb7f"

[[r2_buckets]]
binding = "r2"
bucket_name = "nextjs-app-r2"